name: Build Kivy APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip openjdk-17-jdk python3-pip wget unzip
          pip3 install --upgrade pip setuptools wheel cython buildozer python-for-android kivy kivymd pillow

      - name: Install Android SDK & AIDL
        run: |
          # Set environment variables
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          # Download and install Android SDK command-line tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip
          
          # Accept Android licenses
          yes | sdkmanager --licenses
          
          # Install necessary SDK components
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "cmdline-tools;latest"

      - name: Modify Buildozer Spec
        run: |
          sed -i 's/# android.ndk = 19c/android.ndk = 21b/g' buildozer.spec
          sed -i 's/# android.api = 27/android.api = 31/g' buildozer.spec
          sed -i 's/# android.minapi = 21/android.minapi = 21/g' buildozer.spec
          sed -i 's/# android.archs = arm64-v8a armeabi-v7a/android.archs = arm64-v8a armeabi-v7a/g' buildozer.spec
          sed -i 's/# requirements = python3,kivy/requirements = python3,kivy,kivymd,pillow/g' buildozer.spec

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RacingGame-APK
          path: bin/*.apk
